-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- PROFILES (Users)
create table profiles (
  id uuid references auth.users on delete cascade primary key,
  full_name text,
  avatar_url text,
  phone text,
  role text default 'user' check (role in ('user', 'admin')),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- CATS (Adoption Listings)
create table cats (
  id bigint generated by default as identity primary key,
  name text not null,
  age integer not null, -- months or years, stored as number (maybe store months for precision)
  gender text not null check (gender in ('Male', 'Female')),
  breed text,
  location text not null,
  description text,
  attributes jsonb default '{}'::jsonb, -- { vaccinated: true, neutered: false, etc }
  images text[] default '{}',
  status text default 'Available' check (status in ('Available', 'Adopted', 'Pending')),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- MEMORIALS (Tributes)
create table memorials (
  id bigint generated by default as identity primary key,
  pet_name text not null,
  owner_name text not null,
  tribute text not null,
  image_url text,
  user_id uuid references auth.users(id),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- REPORTS (Lost & Found)
create table reports (
  id bigint generated by default as identity primary key,
  type text not null check (type in ('Lost', 'Found', 'Injured')),
  description text,
  latitude double precision,
  longitude double precision,
  location_text text,
  contact_info text,
  image_url text,
  user_id uuid references auth.users(id),
  status text default 'Open' check (status in ('Open', 'Resolved')),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- VETS (Clinics)
create table vets (
  id bigint generated by default as identity primary key,
  name text not null,
  address text not null,
  phone text,
  latitude double precision,
  longitude double precision,
  rating numeric(2,1) default 0,
  services text[] default '{}',
  website text,
  image_url text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- ADOPTION APPLICATIONS
create table adoption_applications (
  id bigint generated by default as identity primary key,
  cat_id bigint references cats(id),
  user_id uuid references auth.users(id),
  status text default 'Pending' check (status in ('Pending', 'Approved', 'Rejected')),
  form_data jsonb not null, -- Stores the full application answers
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- ROW LEVEL SECURITY (RLS) policies

-- Enable RLS on all tables
alter table profiles enable row level security;
alter table cats enable row level security;
alter table memorials enable row level security;
alter table reports enable row level security;
alter table vets enable row level security;
alter table adoption_applications enable row level security;

-- PROFILES
create policy "Public profiles are viewable by everyone" 
  on profiles for select using (true);

create policy "Users can insert their own profile" 
  on profiles for insert with check (auth.uid() = id);

create policy "Users can update own profile" 
  on profiles for update using (auth.uid() = id);

-- CATS
create policy "Cats are viewable by everyone" 
  on cats for select using (true);

create policy "Admins can insert/update cats" 
  on cats for all using (
    exists (select 1 from profiles where id = auth.uid() and role = 'admin')
  );

-- MEMORIALS
create policy "Memorials are viewable by everyone" 
  on memorials for select using (true);

create policy "Authenticated users can create memorials" 
  on memorials for insert with check (auth.role() = 'authenticated');

-- REPORTS
create policy "Reports are viewable by everyone" 
  on reports for select using (true);

create policy "Authenticated users can create reports" 
  on reports for insert with check (auth.role() = 'authenticated');

create policy "Users can update their own reports" 
  on reports for update using (auth.uid() = user_id);

-- VETS
create policy "Vets are viewable by everyone" 
  on vets for select using (true);

-- ADOPTION APPLICATIONS
create policy "Users can view their own applications" 
  on adoption_applications for select using (auth.uid() = user_id);

create policy "Admins can view all applications" 
  on adoption_applications for select using (
    exists (select 1 from profiles where id = auth.uid() and role = 'admin')
  );

create policy "Authenticated users can submit applications" 
  on adoption_applications for insert with check (auth.role() = 'authenticated');

-- FUNCTIONS
-- Initial data or helper functions can be added here if needed

-- STORAGE BUCKETS
insert into storage.buckets (id, name, public) 
values 
  ('memorials', 'memorials', true),
  ('reports', 'reports', true),
  ('cats', 'cats', true),
  ('avatars', 'avatars', true)
on conflict (id) do nothing;

-- STORAGE POLICIES
-- Allow public access to all files in these buckets
create policy "Public Access" 
  on storage.objects for select 
  using ( bucket_id in ('memorials', 'reports', 'cats', 'avatars') );

-- Allow authenticated users to upload files
create policy "Authenticated users can upload" 
  on storage.objects for insert 
  with check ( auth.role() = 'authenticated' );

-- Allow users to update/delete their own files (if referenced by user_id metadata if you set it, or simplified here)
-- For now, we'll keep it simple: authenticated users can insert. 
-- In a real app, you'd want stricter policies (e.g. only vets/admins upload to cats).

